# Build phase
FROM node:18 AS build
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build -- --mode production

# Serve phase (dùng nginx)
FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf

# Port mặc định Cloud Run là 8080
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
